blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
]


urlpatterns = urlpatterns + static(
    settings.MEDIA_URL,  document_root = settings.MEDIA_ROOT
    )

blog/home/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    # path('', BlogListView.as_view(), name = 'home'),
    path('', home, name = 'home'),
    path('register/', register, name = 'register'),
    path('login/', login, name = 'login'),
    path('logout/', logout, name = 'logout'),

    path('profile/<str:username>/', profile, name = 'profile'),
    path('profile/<str:username>/delete/', delete_acc, name = 'delete_acc'),

    path('blog/<int:pk>/', blogDetail, name = 'blog-detail'),
]

blog/home/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='media_profile_model', blank=True, null=True)

    def __str__(self):
        return f"{self.user.username}'s profile"
    
    @property
    def img_url(self):
        try:
            return f"{self.image.url}"
    
        except Exception as ex:
            return f"/static/images/static_profile_model/default.png"




class Blog(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField()
    created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return f"{self.title} | {self.author.username}"




class Tag(models.Model):
    name = models.CharField(max_length=200)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} | {self.blog.title}"

blog/home/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.core.exceptions import ValidationError
from .models import Profile



class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
    
    def clean_email(self):

        email = self.cleaned_data.get('email')
        if User.objects.filter(email = email).exists():
            raise ValidationError("This Email Is Already Taken!")
        return email




class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

blog/home/views.py
from django.shortcuts import render, redirect
from .forms import UserRegistrationForm, UserUpdateForm, ProfileUpdateForm
from django.contrib import messages
from django.contrib.auth.models import User, auth
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView
from . models import Profile, Blog, Tag
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from . utils import search_blog

# class BlogListView(ListView):
#     model = Blog
#     template_name = 'home/index.html'
#     context_object_name = 'blogs'
#     paginate_by = 2
#     ordering = ['created']



def home(request):
    
    blogs,query_value = search_blog(request)

    page = request.GET.get('page') if request.GET.get('page') else ''
    result = 2

    paginator = Paginator(blogs, result)

    try:
        blogs = paginator.page(page)
    
    except PageNotAnInteger as ex1:
        blogs = paginator.page('1')
    
    except EmptyPage as ex2:
        page = paginator.num_pages
        blogs = paginator.page(page)

    context = {'blogs':blogs, 'query_value':query_value}
    return render(request, 'home/index.html', context)


def blogDetail(request, pk):
    blog = Blog.objects.get(pk = pk)
    context = {'blog':blog}
    return render(request, 'home/blog_detail.html', context)


def register(request):
    form = UserRegistrationForm()
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():

            new_user = form.save(commit=False)
            username = new_user.username.lower()
            new_user.username = username
            new_user.save()

            auth.login(request, new_user)
            messages.success(request, 'Account Created Successfully!')
            return redirect('home')
    context = {'form': form}
    return render(request, 'home/register.html', context)


def login(request):
    if request.user.is_authenticated:
        messages.info(request, 'You\'ve Already Loged-In!')
        return redirect('home')
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        auth_user = auth.authenticate(username = username, password = password)
        if auth_user is not None:
            auth.login(request, auth_user)
            messages.success(request, 'Successfully Loged In!')
            return redirect('home')
        else:
            messages.error(request, "User doesn't Exist!")
            return redirect('login')
    return render(request, 'home/login.html')


def logout(request):
    if not(request.user.is_authenticated):
        messages.info(request, "You've Not Loged-In!")
        return redirect('home')
    auth.logout(request)
    messages.success(request, 'Loged-Out Successfully!')
    return redirect('home')


@login_required
def profile(request, username):
    current_user = User.objects.get(username = username)
    if request.user != current_user:
        return HttpResponse("<h1>Forbidden 403</h1>")
    u_form = UserUpdateForm(instance=current_user)
    p_form = ProfileUpdateForm(instance=current_user.profile)

    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=current_user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=current_user.profile)

        if u_form.is_valid() and p_form.is_valid():
            alt_user = u_form.save()
            p_form.save()

            messages.success(request, "Porfile Updated Successfully!")
            return redirect(profile, username=alt_user.username)

    context = {'current_user':current_user, 'u_form':u_form, 'p_form':p_form}
    return render(request, 'home/profile.html', context)


@login_required
def delete_acc(request, username):
    current_user = User.objects.get(username = username)
    profile = current_user.profile
    if request.user != current_user:
        return HttpResponse("<h1>Forbidden 403</h1>")

    if request.method == 'POST':
        profile.delete()
        messages.success(request, "Account Deleted Successfully")
        return redirect('home')


    context = {'current_user':current_user}
    return render(request, 'home/delete_profile.html', context)

blog/home/templates/home/blog_detail.html
{% extends 'base.html' %}


{% block content2 %}

        <hr>
            username :- {{blog.author.username}} <br>
            title :- {{blog.title}} <br>
            description :- {{blog.description}} <br>
            Tags : - 
            {% for tag in blog.tag_set.all %}
                |&nbsp;{{tag.name}}
            {% endfor %}
        <hr>

        <a href="
            {% if request.GET.back %}
            {{request.GET.back}}
            {% else %}
            {% url 'home' %}
            {% endif %}
        ">Back</a>



{% endblock content2 %}

blog/home/templates/home/delete_profile.html
{% extends 'base.html' %}


{% block content2 %}

    
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}

            Are U Sure U Want To Delete '{{current_user.username}}'s profile :)?

        <button type="submit">Delete</button>
        &nbsp;&nbsp;
        <a href="
            {% if request.GET.back %}
            {{request.GET.back}}
            {% else %}
            {% url 'home' %}
            {% endif %}        
        ">Back</a>
    </form>

{% endblock content2 %}

blog/home/templates/home/index.html
{% extends 'base.html' %}

{% block content2 %}
    <br><br>
    <form action="" method="GET" id="blog_form">
        <input type="text" value="{{query_value}}" name="query" placeholder="Search any...">
        &nbsp;        &nbsp;
        <button type="submit">Search</button>
    </form>
    <br>

    {% for blog in blogs %}
        <hr>
            username :- {{blog.author.username}} <br>
            title :- <a href="{% url 'blog-detail' blog.pk %}?back={{request.path}}">{{blog.title}}</a> <br>
            description :- {{blog.description}} <br>
            Tags : - 
            {% for tag in blog.tag_set.all %}
                |&nbsp;{{tag.name}}
            {% endfor %}
        <hr>
        <br><br>
    {% endfor %}


    {% include 'pagination.html' with queryset=blogs %}


{% endblock content2 %}

blog/home/templates/home/login.html
{% extends 'base.html' %}


{% block content2 %}

    <h1>Login Here!</h1>
    
    <form action="" method="POST">
        {% csrf_token %}

        <label for="">Username :- </label> <br>
        <input type="text" name="username" required>

        <br><br>

        <label for="">Password</label> <br>
        <input type="password" name="password" required>

        <br><br>

        <button type="submit">Login</button>
    </form>

{% endblock content2 %}

blog/home/templates/home/profile.html
{% extends 'base.html' %}


{% block content2 %}

    Username :- {{current_user.username}}
    <br><br>
    Email :- {{current_user.email}}
    <br><br>
    <img src="{{current_user.profile.img_url}}" alt="profile_pic" width="150px" height="150px">
    
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}

            {{u_form.as_p}}
            {{p_form.as_p}}

        <button type="submit">Update</button>
        &nbsp;&nbsp;
        <a href="{% url 'delete_acc' current_user.username %}?back={{request.path}}">Delete</a>
    </form>

{% endblock content2 %}

blog/home/templates/home/register.html
{% extends 'base.html' %}


{% block content2 %}

    <h1>Join Today</h1>

    <form action="" method="POST">
        {% csrf_token %}

        {{form.as_p}}

        <button type="submit">Register</button>
    </form>

{% endblock content2 %}

blog/templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    {% include 'navbar.html' %}

    {% block content2 %}
    {% endblock content2 %}


    <script src="{% static 'js/script.js' %}"></script>


</body>
</html>

blog/templates/navbar.html
<a href="{% url 'home' %}">
    <h1>
        Logo
    </h1>
</a>


{% if messages %}
    {% for message in messages %}
        <h4>
            <b class="msg" style="
            background-color: antiquewhite; padding: 1em; border: 1px solid black;">{{message}}</b>
        </h4>
    {% endfor %}
{% endif %}


{% if request.user.is_authenticated %}
        <a href="{% url 'home' %}">Home</a> &nbsp;&nbsp;
        <a href="{% url 'profile' request.user.username  %}">Profile</a> &nbsp;&nbsp;
        <a href="{% url 'logout' %}">Logout</a> &nbsp;&nbsp;
{% else %}
        <a href="{% url 'register' %}">Register</a> &nbsp;&nbsp;
        <a href="{% url 'login' %}">Login</a> &nbsp;&nbsp;
{% endif %}

blog/templates/pagination.html
{% if queryset.has_other_pages %}
    {% if queryset.has_previous %}
        <a href="?page=1" class="page" data-page="1" >First</a>
        <a href="?page={{queryset.previous_page_number}}" 
        data-page="{{queryset.previous_page_number}}" class="page">Last</a>
    {% endif %}


    {% for num in queryset.paginator.page_range %}
        {% if num == queryset.number %}
            <a href="?page={{num}}" data-page="{{num}}" class="page"
                style="background-color: aqua; border: 1px solid black; padding: 0.5em;"
            >{{num}}</a>
        {% elif num > queryset.number|add:'-3' and num < queryset.number|add:'3' %}
            <a data-page="{{num}}" class="page" href="?page={{num}}" class="page">{{num}}</a>
        {% endif %}
    {% endfor %}


    {% if queryset.has_next %}
        <a href="?page={{queryset.next_page_number}}" data-page="{{queryset.next_page_number}}" class="page">Next</a>
        <a href="?page={{queryset.paginator.num_pages}}" data-page="{{queryset.paginator.num_pages}}" class="page">Last</a>
    {% endif %}
{% endif %}